export const data = [
  {label: '4 / 6 pack rings',categories:['Non-specific plastic']},
  {label: 'Carrier',categories:['Non-specific plastic','Bags']},
  {label: 'Packaging',categories:['Non-specific plastic','Bags']},
  {label: 'Other',categories:['Non-specific plastic','Bags']},
  {label: 'Drinks',categories:['Non-specific plastic','Bottles and containers']},
  {label: 'Cleaning products',categories:['Non-specific plastic','Bottles and containers']},
  {label: 'Food (e.g. pots, tubs, sachets)',categories:['Non-specific plastic','Bottles and containers']},
  {label: 'Toiletries',categories:['Non-specific plastic','Bottles and containers']},
  {label: 'Caps / lids',categories:['Non-specific plastic']},
  {label: 'Cigarette lighters',categories:['Non-specific plastic']},
  {label: 'Tobacco pouches',categories:['Non-specific plastic']},
  {label: 'Cigarette buts',categories:['Non-specific plastic']},
  {label: 'Combs / hair brushes',categories:['Non-specific plastic']},
  {label: 'Sunglasses',categories:['Non-specific plastic']},
  {label: 'Crisp wrappers',categories:['Non-specific plastic']},
  {label: 'Sandwich packaging',categories:['Non-specific plastic']},
  {label: 'Pasta pots',categories:['Non-specific plastic']},
  {label: 'Chocolate wrappers',categories:['Non-specific plastic']},
  {label: 'Sweet wrappers',categories:['Non-specific plastic']},
  {label: 'Cutlery',categories:['Non-specific plastic']},
  {label: 'Trays (e.g. meat trays)',categories:['Non-specific plastic']},
  {label: 'Straws',categories:['Non-specific plastic']},
  {label: 'Disposable cups (not paper)',categories:['Non-specific plastic']},
  {label: 'Disposable cup lids',categories:['Non-specific plastic']},
  {label: 'Fishing line',categories:['Non-specific plastic','Fishing']},
  {label: 'Fishing net and net pieces (< 50cm)',categories:['Non-specific plastic','Fishing']},
  {label: 'Fishing net and net pieces (> 50cm)',categories:['Non-specific plastic','Fishing']},
  {label: 'Fishing floats and reels',categories:['Non-specific plastic','Fishing']},
  {label: 'Industrial packaging / crates / sheeting',categories:['Non-specific plastic']},
  {label: 'Mesh bags (e.g. fruit / vegetable)',categories:['Non-specific plastic']},
  {label: 'Pallets / crates',categories:['Non-specific plastic']},
  {label: 'Stationary',categories:['Non-specific plastic']},
  {label: 'Rope (diameter > 1cm)',categories:['Non-specific plastic']},
  {label: 'String / cord (diameter < 1cm)',categories:['Non-specific plastic']},
  {label: 'Toys',categories:['Non-specific plastic']},
  {label: 'Balloon string',categories:['Non-specific plastic']},
  {label: 'Traffic cones',categories:['Non-specific plastic']},
  {label: 'Plastic pieces (<2.5 cm)',categories:['Non-specific plastic']},
  {label: 'Plastic pieces (>2.5 cm)',categories:['Non-specific plastic']},
  {label: 'Other (Specify)',categories:['Non-specific plastic']},
  {label: 'Fast food containers',categories:['Specific plastic','Polystyrene']},
  {label: 'Foam / sponge insulation',categories:['Specific plastic','Polystyrene']},
  {label: 'Packaging',categories:['Specific plastic','Polystyrene']},
  {label: 'Polystyrene pieces (< 50 cm)',categories:['Specific plastic','Polystyrene']},
  {label: 'Polystyrene pieces (5-50 cm)',categories:['Specific plastic','Polystyrene']},
  {label: 'Polystyrene pieces (> 50 cm)',categories:['Specific plastic','Polystyrene']},
  {label: 'Individual polystyrene beads',categories:['Specific plastic','Polystyrene']},
  {label: 'Other (specify)',categories:['Specific plastic','Polystyrene']},

  {label: 'Balloons',categories:['Specific plastic','Rubber']},
  {label: 'Gloves (heavy duty)',categories:['Specific plastic','Rubber']},
  {label: 'Gloves (light weight)',categories:['Specific plastic','Rubber']},
  {label: 'Rubber pieces (< 50 cm)',categories:['Specific plastic','Rubber']},
  {label: 'Bike',categories:['Specific plastic','Rubber','Tyres (no wheel)']},
  {label: 'Car',categories:['Specific plastic','Rubber','Tyres (no wheel)']},
  {label: 'Other - Non specific plastic',categories:['Specific plastic','Rubber','Tyres (no wheel)']},
  {label: 'Bike',categories:['Specific plastic','Rubber','Tyres (with wheel)']},
  {label: 'Car',categories:['Specific plastic','Rubber','Tyres (with wheel)']},
  {label: 'Other - Non specific plastic',categories:['Specific plastic','Rubber','Tyres (with wheel)']},
  {label: 'Other (specify)',categories:['Specific plastic','Rubber']},

  {label: 'Inhaler',categories:['Specific plastic','Medical']},
  {label: 'Plasters',categories:['Specific plastic','Medical']},
  {label: 'Syringes',categories:['Specific plastic','Medical']},
  {label: 'Other (specify)',categories:['Specific plastic','Medical']},

  {label: 'Condoms',categories:['Specific plastic','Sanitary']},
  {label: 'Cotton bud sticks',categories:['Specific plastic','Sanitary']},
  {label: 'Nappies',categories:['Specific plastic','Sanitary']},
  {label: 'Tampon applicators / tampons',categories:['Specific plastic','Sanitary']},
  {label: 'Toilet fresheners',categories:['Specific plastic','Sanitary']},
  {label: 'Towels',categories:['Specific plastic','Sanitary']},
  {label: 'Wet wipes',categories:['Specific plastic','Sanitary']},
  {label: 'Other (specify)',categories:['Specific plastic','Sanitary']},

  {label: 'In bags',categories:['Specific plastic','Animal faces (Don not touch!)']},
  {label: 'Not in bags',categories:['Specific plastic','Animal faces (Don not touch!)']},

  {label: 'Cloth pieces',categories:['Other','Cloth / clothing']},
  {label: 'Clothing',categories:['Other','Cloth / clothing']},
  {label: 'Footwear',categories:['Other','Cloth / clothing']},
  {label: 'Sacking',categories:['Other','Cloth / clothing']},
  {label: 'Other (specify)',categories:['Other','Cloth / clothing']},

  {label: 'Aerosol cans',categories:['Other','Metal']},
  {label: 'BBQs (disposable)',categories:['Other','Metal']},
  {label: 'Bottle caps',categories:['Other','Metal']},
  {label: 'Car parts / car batteries',categories:['Other','Metal']},
  {label: 'Drinks cans',categories:['Other','Metal']},
  {label: 'Fishing weights / hooks / lures',categories:['Other','Metal']},
  {label: 'Foil wrappers',categories:['Other','Metal']},
  {label: 'Food cans',categories:['Other','Metal']},
  {label: 'Scrap / Metal appliances / paint tins',categories:['Other','Metal']},
  {label: 'Household batteries',categories:['Other','Metal']},
  {label: 'Wire / wire mesh',categories:['Other','Metal']},
  {label: 'Metal pieces',categories:['Other','Metal']},
  {label: 'Other (specify)',categories:['Other','Metal']},

  {label: 'Corks',categories:['Other','Wood']},
  {label: 'Pallets / crates',categories:['Other','Wood']},
  {label: 'Ice lolly sticks / chip forks',categories:['Other','Wood']},
  {label: 'Paint brushes',categories:['Other','Wood']},
  {label: 'Wood pieces (not twigs etc.)',categories:['Other','Wood']},
  {label: 'Other (specify)',categories:['Other','Wood']},

  {label: 'Bottles',categories:['Other','Glass']},
  {label: 'Light bulbs / tubes',categories:['Other','Glass']},
  {label: 'Glass pieces',categories:['Other','Glass']},

  {label: 'Any pottery / ceramic',categories:['Other','Pottery / ceramic']},
]
